const SET_ARTISTS = 'SET_ARTISTS';
const SET_ARTISTS_TYPEAHEAD = 'SET_ARTISTS_TYPEAHEAD';
const SET_ARTISTS_TYPEAHEAD_DICT = 'SET_ARTISTS_TYPEAHEAD_DICT';
const SET_COLORS = 'SET_COLORS';
const SET_EDITING_ARTIST = 'SET_EDITING_ARTIST';
const SET_EDITING_MEMBERS = 'SET_EDITING_MEMBERS';
const SET_EDITING_UNIT = 'SET_EDITING_UNIT';
const SET_MEMBERS = 'SET_MEMBERS';
const SET_MEMBERS_TYPEAHEAD = 'SET_MEMBERS_TYPEAHEAD';
const SET_MEMBERS_TYPEAHEAD_DICT = 'SET_MEMBERS_TYPEAHEAD_DICT';
const SET_PANELS = 'SET_PANELS';
const SET_UI_REFERENCE_TAB = 'SET_UI_REFERENCE_TAB';

export default {
  SET_ARTISTS,
  SET_ARTISTS_TYPEAHEAD,
  SET_ARTISTS_TYPEAHEAD_DICT,
  SET_COLORS,
  SET_EDITING_ARTIST,
  SET_EDITING_MEMBERS,
  SET_EDITING_UNIT,
  SET_MEMBERS,
  SET_MEMBERS_TYPEAHEAD,
  SET_MEMBERS_TYPEAHEAD_DICT,
  SET_PANELS,
  SET_UI_REFERENCE_TAB,
};
