const SET_COLORS_IN_USE = 'SET_COLORS_IN_USE';
const SET_CREATE_SUCCESS = 'SET_CREATE_SUCCESS';
const SET_EDITING_ARTIST = 'SET_EDITING_ARTIST';
const SET_EDITING_MEMBERS = 'SET_EDITING_MEMBERS';
const SET_EDITING_UNIT = 'SET_EDITING_UNIT';
const SET_MANAGE_RESULT = 'SET_MANAGE_RESULT';
const SET_PANELS = 'SET_PANELS';
const SET_UNITS_TYPEAHEAD = 'SET_UNITS_TYPEAHEAD';
const SET_UNITS_TYPEAHEAD_DICT = 'SET_UNITS_TYPEAHEAD_DICT';

export default {
  SET_COLORS_IN_USE,
  SET_CREATE_SUCCESS,
  SET_EDITING_ARTIST,
  SET_EDITING_MEMBERS,
  SET_EDITING_UNIT,
  SET_MANAGE_RESULT,
  SET_PANELS,
  SET_UNITS_TYPEAHEAD,
  SET_UNITS_TYPEAHEAD_DICT,
};
