const SET_ARTISTS = 'SET_ARTISTS';
const SET_ARTISTS_TYPEAHEAD = 'SET_ARTISTS_TYPEAHEAD';
const SET_ARTISTS_TYPEAHEAD_DICT = 'SET_ARTISTS_TYPEAHEAD_DICT';
const SET_COLORS = 'SET_COLORS';
const SET_CREATE_SUCCESS = 'SET_CREATE_SUCCESS';
const SET_EDITING_ARTIST = 'SET_EDITING_ARTIST';
const SET_EDITING_MEMBERS = 'SET_EDITING_MEMBERS';
const SET_EDITING_UNIT = 'SET_EDITING_UNIT';
const SET_MANAGE_RESULT = 'SET_MANAGE_RESULT';
const SET_MEMBERS = 'SET_MEMBERS';
const SET_MEMBERS_TYPEAHEAD = 'SET_MEMBERS_TYPEAHEAD';
const SET_MEMBERS_TYPEAHEAD_DICT = 'SET_MEMBERS_TYPEAHEAD_DICT';
const SET_PANELS = 'SET_PANELS';
const SET_UI_REFERENCE_TAB = 'SET_UI_REFERENCE_TAB';
const SET_UNITS_TYPEAHEAD = 'SET_UNITS_TYPEAHEAD';
const SET_UNITS_TYPEAHEAD_DICT = 'SET_UNITS_TYPEAHEAD_DICT';

export default {
  SET_ARTISTS,
  SET_ARTISTS_TYPEAHEAD,
  SET_ARTISTS_TYPEAHEAD_DICT,
  SET_COLORS,
  SET_CREATE_SUCCESS,
  SET_EDITING_ARTIST,
  SET_EDITING_MEMBERS,
  SET_EDITING_UNIT,
  SET_MANAGE_RESULT,
  SET_MEMBERS,
  SET_MEMBERS_TYPEAHEAD,
  SET_MEMBERS_TYPEAHEAD_DICT,
  SET_PANELS,
  SET_UI_REFERENCE_TAB,
  SET_UNITS_TYPEAHEAD,
  SET_UNITS_TYPEAHEAD_DICT,
};
