const SET_ARTISTS = 'SET_ARTISTS';
const SET_ARTISTS_TYPEAHEAD = 'SET_ARTISTS_TYPEAHEAD';
const SET_ARTISTS_TYPEAHEAD_DICT = 'SET_ARTISTS_TYPEAHEAD_DICT';
const SET_COLORS = 'SET_COLORS';
const SET_MEMBERS = 'SET_MEMBERS';
const SET_MEMBERS_TYPEAHEAD = 'SET_MEMBERS_TYPEAHEAD';
const SET_MEMBERS_TYPEAHEAD_DICT = 'SET_MEMBERS_TYPEAHEAD_DICT';
const SET_SONGS = 'SET_SONGS';
const SET_SONG_SEARCH_QUERY = 'SET_SONG_SEARCH_QUERY';

export default {
  SET_ARTISTS,
  SET_ARTISTS_TYPEAHEAD,
  SET_ARTISTS_TYPEAHEAD_DICT,
  SET_COLORS,
  SET_MEMBERS,
  SET_MEMBERS_TYPEAHEAD,
  SET_MEMBERS_TYPEAHEAD_DICT,
  SET_SONGS,
  SET_SONG_SEARCH_QUERY,
};
