const SET_ARTISTS = 'SET_ARTISTS';
const SET_ARTISTS_TYPEAHEAD = 'SET_ARTISTS_TYPEAHEAD';
const SET_ARTISTS_TYPEAHEAD_DICT = 'SET_ARTISTS_TYPEAHEAD_DICT';
const SET_COLORS = 'SET_COLORS';
const SET_DB_RELOAD = 'SET_DB_RELOAD';
const SET_MEMBERS = 'SET_MEMBERS';
const SET_MEMBERS_TYPEAHEAD = 'SET_MEMBERS_TYPEAHEAD';
const SET_MEMBERS_TYPEAHEAD_DICT = 'SET_MEMBERS_TYPEAHEAD_DICT';
const SET_SONGS = 'SET_SONGS';

export default {
  SET_ARTISTS,
  SET_ARTISTS_TYPEAHEAD,
  SET_ARTISTS_TYPEAHEAD_DICT,
  SET_COLORS,
  SET_DB_RELOAD,
  SET_MEMBERS,
  SET_MEMBERS_TYPEAHEAD,
  SET_MEMBERS_TYPEAHEAD_DICT,
  SET_SONGS,
};
