const RESET_SYNC = 'RESET_SYNC';
const SET_ACTIVE_LINE = 'SET_ACTIVE_LINE';
const SET_ACTIVE_PILL = 'SET_ACTIVE_PILL';
const SET_ARE_LYRICS_LOCKED = 'SET_ARE_LYRICS_LOCKED';
const SET_FINAL_LYRICS = 'SET_FINAL_LYRICS';
const SET_INFO = 'SET_INFO';
const SET_IS_DISTRIBUTION_COMPLETE = 'SET_IS_DISTRIBUTION_COMPLETE';
const SET_LINK_SEQUENCE_MODE = 'SET_LINK_SEQUENCE_MODE';
const SET_LAST_ID_NUM = 'SET_LAST_ID_NUM';
const SET_LYRICS = 'SET_LYRICS';
const SET_PILLS = 'SET_PILLS';
const SET_QUEUE = 'SET_QUEUE';
const SET_STEP = 'SET_STEP';
const SET_STEPS = 'SET_STEPS';
const SET_SYNC_DISTRIBUTION_LINES = 'SET_SYNC_DISTRIBUTION_LINES';
const SET_SYNC_STATS = 'SET_SYNC_STATS';
const SET_TIMESTAMPS = 'SET_TIMESTAMPS';
const SET_VIDEO_ID = 'SET_VIDEO_ID';

export default {
  RESET_SYNC,
  SET_ACTIVE_LINE,
  SET_ACTIVE_PILL,
  SET_ARE_LYRICS_LOCKED,
  SET_FINAL_LYRICS,
  SET_INFO,
  SET_IS_DISTRIBUTION_COMPLETE,
  SET_LINK_SEQUENCE_MODE,
  SET_LAST_ID_NUM,
  SET_LYRICS,
  SET_PILLS,
  SET_QUEUE,
  SET_STEP,
  SET_STEPS,
  SET_SYNC_DISTRIBUTION_LINES,
  SET_SYNC_STATS,
  SET_TIMESTAMPS,
  SET_VIDEO_ID,
};
