export const GENDERS = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
  UNKOWN: 'UNKNOWN',
};

export const GENRES = {
  CPOP: 'C-POP',
  JPOP: 'J-POP',
  KPOP: 'K-POP',
  OTHER: 'OTHER',
  POP: 'POP',
};

export const POSITIONS = {
  LEADER: 'LEADER',
  MAIN_VOCALIST: 'MAIN_VOCALIST',
  MAIN_RAPPER: 'MAIN_RAPPER',
  MAIN_DANCER: 'MAIN_DANCER',
  LEAD_VOCALIST: 'LEAD_VOCALIST',
  LEAD_RAPPER: 'LEAD_RAPPER',
  LEAD_DANCER: 'LEAD_DANCER',
  VOCALIST: 'VOCALIST',
  RAPPER: 'RAPPER',
  DANCER: 'DANCER',
  CENTER: 'CENTER',
  FACE_OF_THE_GROUP: 'FACE_OF_THE_GROUP',
  VISUAL: 'VISUAL',
  MAKNAE: 'MAKNAE',
};
