const SET_ACTIVE_MEMBER_PILL = 'SET_ACTIVE_MEMBER_PILL';
const SET_ACTIVE_SONG = 'SET_ACTIVE_SONG';
const SET_ACTIVE_UNIT = 'SET_ACTIVE_UNIT';
const SET_DISTRIBUTION_LINES = 'SET_DISTRIBUTION_LINES';
const SET_RATES = 'SET_RATES';

export default {
  SET_ACTIVE_MEMBER_PILL,
  SET_ACTIVE_SONG,
  SET_ACTIVE_UNIT,
  SET_DISTRIBUTION_LINES,
  SET_RATES,
};
