const RESET_DISTRIBUTE = 'RESET_DISTRIBUTE';
const RESET_DISTRIBUTE_SONG = 'RESET_DISTRIBUTE_SONG';
const SET_ACTIVE_MEMBER_PILL = 'SET_ACTIVE_MEMBER_PILL';
const SET_ACTIVE_SONG = 'SET_ACTIVE_SONG';
const SET_ACTIVE_UNIT = 'SET_ACTIVE_UNIT';
const SET_DISTRIBUTE_VIEW = 'SET_DISTRIBUTE_VIEW';
const SET_DISTRIBUTION_CATEGORY = 'SET_DISTRIBUTION_CATEGORY';
const SET_DISTRIBUTION_LINES = 'SET_DISTRIBUTION_LINES';
const SET_DISTRIBUTION_REMAINDER = 'SET_DISTRIBUTION_REMAINDER';
const SET_RATES = 'SET_RATES';

export default {
  RESET_DISTRIBUTE,
  RESET_DISTRIBUTE_SONG,
  SET_ACTIVE_MEMBER_PILL,
  SET_ACTIVE_SONG,
  SET_ACTIVE_UNIT,
  SET_DISTRIBUTE_VIEW,
  SET_DISTRIBUTION_CATEGORY,
  SET_DISTRIBUTION_LINES,
  SET_DISTRIBUTION_REMAINDER,
  SET_RATES,
};
