const SET_DATABASE_READY = 'SET_DATABASE_READY';
const SET_ERROR = 'SET_ERROR';
const SET_ERROR_INLINE = 'SET_ERROR_INLINE';
const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
const SET_LOADING = 'SET_LOADING';
const SET_PENDING = 'SET_PENDING';
const SET_SUCCESS = 'SET_SUCCESS';
const SET_SUCCESS_INLINE = 'SET_SUCCESS_INLINE';
const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';

export default {
  SET_DATABASE_READY,
  SET_ERROR,
  SET_ERROR_INLINE,
  SET_ERROR_MESSAGE,
  SET_LOADING,
  SET_PENDING,
  SET_SUCCESS,
  SET_SUCCESS_INLINE,
  SET_SUCCESS_MESSAGE,
};
