const SET_ACTIVE_UNIT = 'SET_ACTIVE_UNIT';
const SET_ARTIST_LIST = 'SET_ARTIST_LIST';
const SET_ARTIST_PAGE_TAB = 'SET_ARTIST_PAGE_TAB';
const SET_BIAS = 'SET_BIAS';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
const SET_SELECTED_ARTIST = 'SET_SELECTED_ARTIST';
const SET_SELECTED_UNIT = 'SET_SELECTED_UNIT';
const SET_SHOW_FAVORITE_ARTISTS_ONLY = 'SET_SHOW_FAVORITE_ARTISTS_ONLY';

export default {
  SET_ACTIVE_UNIT,
  SET_ARTIST_LIST,
  SET_ARTIST_PAGE_TAB,
  SET_BIAS,
  SET_SEARCH_QUERY,
  SET_SELECTED_ARTIST,
  SET_SELECTED_UNIT,
  SET_SHOW_FAVORITE_ARTISTS_ONLY,
};
