const SET_ARTIST_LIST = 'SET_ARTIST_LIST';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
const SET_SELECTED_ARTIST = 'SET_SELECTED_ARTIST';

export default {
  SET_ARTIST_LIST,
  SET_SEARCH_QUERY,
  SET_SELECTED_ARTIST,
};
