const SET_ARTIST_LIST = 'SET_ARTIST_LIST';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
const SET_SELECTED_ARTIST = 'SET_SELECTED_ARTIST';
const SET_SHOW_FAVORITE_ARTISTS_ONLY = 'SET_SHOW_FAVORITE_ARTISTS_ONLY';

export default {
  SET_ARTIST_LIST,
  SET_SEARCH_QUERY,
  SET_SELECTED_ARTIST,
  SET_SHOW_FAVORITE_ARTISTS_ONLY,
};
