const SET_ADMIN = 'SET_ADMIN';
const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
const SET_BIASES = 'SET_BIASES';
const SET_USER = 'SET_USER';

export default {
  SET_ADMIN,
  SET_AUTHENTICATED,
  SET_BIASES,
  SET_USER,
};
